language: node_js
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
node_js:
  - 'node'
install:
  - 'npm install'
script:
  - 'npm run codecov'
  - 'npm run e2e'
